language: node_js
node_js:
  - lts/*

jobs:
  include:
    - stage: install
      script:
        - yarn
      skip_cleanup: true
    - stage: Build & publish
      script:
        - yarn build
        - yarn semantic-release
      if: branch = master
